#include "web_ui_internal.h"
#include "esp_log.h"

#define TAG "WEB_UI_TEST_PAGE"

/**
 * @brief Renderizza la pagina `/test` per diagnostica e comandi hardware.
 *
 * La pagina include sezioni collassabili per periferiche e comandi manuali,
 * con JavaScript per invocare gli endpoint sotto il prefisso `/api/test/` e mostrare i risultati.
 *
 * @param req Richiesta HTTP GET.
 * @return ESP_OK se la pagina viene inviata correttamente.
 */
esp_err_t test_page_handler(httpd_req_t *req)
{
    ESP_LOGI(TAG, "[C] GET /test");

    const char *extra_style =
        ".test-item{display:flex;align-items:center;justify-content:space-between;padding:15px;margin:10px 0;background:#ecf0f1;border-radius:6px}"
        ".test-label{font-weight:bold;color:#2c3e50;flex:1}.test-controls{display:flex;gap:10px;align-items:center}"
        "button{padding:8px 16px;background:#e67e22;color:white;border:none;border-radius:4px;cursor:pointer;font-weight:bold;transition:background-color .14s ease, transform .06s ease;outline:none}"
        "button:hover{background:#d35400;transform:translateY(-1px)}button:active{transform:translateY(1px);filter:brightness(0.92)}button:focus-visible{box-shadow:0 0 0 3px rgba(52,152,219,0.18)}"
        ".test-controls button.disabled, .test-controls button:disabled{opacity:0.6; cursor:not-allowed; transform:none}"
        ".btn-stop{background:#e74c3c}.btn-stop:hover{background:#c0392b}"
        "input[type=text],input[type=number]{padding:6px;border:1px solid #bdc3c7;border-radius:4px;width:120px;color:#333}"
        ".status-box{padding:10px;margin:10px 0;border-radius:4px;font-family:monospace;font-size:13px;background:#003366;color:#ffffff;min-height:60px;overflow-y:auto;max-height:250px;border:1px solid #3498db;box-sizing:border-box}"
        ".result{margin:5px 0;padding:5px;border-left:3px solid #3498db}"
        ".refresh-btn{background:#3498db;margin-bottom:10px;transition:background-color .12s ease} .refresh-btn:hover{background:#2980b9} "
        "/* Collapsible sections support */"
        ".section.collapsed > :not(h2){display:none !important;}"
        ".section h2{cursor:pointer; position:relative;}"
        ".section h2 .section-toggle-icon{position:absolute; right:12px; top:6px; font-size:18px; color:#95a5a6;}";

    httpd_resp_set_type(req, "text/html; charset=utf-8");
    send_head(req, "Test Hardware", extra_style, true);

    const char *body =
        "<div class='container'>"
        "<div style='text-align:right;'><button class='refresh-btn' onclick='location.reload()'>🔄 Aggiorna Pagina</button></div>"

        "<div id='section_led' class='section collapsed'><h2>💡 Striscia LED (WS2812) <span style='font-size:14px; color:#bdc3c7'>(PIN 15 / GPIO 5)</span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span class='test-label'>Pattern Rainbow</span>"
        "<div class='test-controls'><button id='btn_led_rainbow' onclick=\"toggleLedRainbow()\">▶️ Inizia Rainbow</button></div></div>"

        "<h3>Controllo Manuale</h3>"
        "<div class='test-item'><span>Seleziona Colore:</span>"
        "<div class='test-controls'>"
        "  <input type='color' id='led_color' value='#ff0000' oninput='updateLedRealtime()' style='width:60px; height:35px; border:none; padding:0; cursor:pointer'>"
        "  <span>Luminosità:</span><input type='range' id='led_bright' min='0' max='100' value='50' oninput='updateLedRealtime()' style='width:100px'>"
        "  <button id='btn_led_manual' onclick=\"toggleLedManual()\" style='background:#2ecc71'>🚀 Inizia Manuale</button>"
        "</div></div>"

        "<div id='led_status' class='status-box'>Pronto per test LED</div></div>"

        "<div id='section_ioexp' class='section collapsed'><h2>🔌 I/O Expander <span style='font-size:14px; color:#bdc3c7'>(PIN 32, 37 / I2C)</span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span class='test-label'>Blink Tutte le Uscite (1Hz)</span>"
        "<div class='test-controls'><button id='btn_ioexp' onclick=\"toggleSimpleTest('ioexp', 'btn_ioexp', 'Blink')\">▶️ Inizia Blink</button></div></div>"

        "<h3>Controllo Manuale</h3>"
        "<div id='io_manual_control' style='display:grid; grid-template-columns: 1fr 1fr; gap: 20px;'>"
        "  <div><h4>Uscite (Chip 0x43)</h4><div id='outputs_grid' style='display:flex; flex-wrap:wrap; gap:5px;'></div></div>"
        "  <div><h4>Ingressi (Chip 0x44)</h4><div id='inputs_grid' style='display:flex; flex-wrap:wrap; gap:5px;'></div></div>"
        "</div>"

        "<div id='ioexp_status' class='status-box'>Pronto per test I/O Expander</div></div>"

        "<div id='section_pwm' class='section collapsed'><h2>⚡ PWM <span style='font-size:14px; color:#bdc3c7'>(PIN 34, 38)</span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span class='test-label'>PWM1 Duty Cycle Sweep</span>"
        "<div class='test-controls'><button id='btn_pwm1' onclick=\"toggleSimpleTest('pwm1', 'btn_pwm1', 'Sweep PWM1')\">▶️ Inizia Sweep</button></div></div>"
        "<div class='test-item'><span class='test-label'>PWM2 Duty Cycle Sweep</span>"
        "<div class='test-controls'><button id='btn_pwm2' onclick=\"toggleSimpleTest('pwm2', 'btn_pwm2', 'Sweep PWM2')\">▶️ Inizia Sweep</button></div></div>"

        "<h3>Controllo Manuale PWM</h3>"
        "<div class='test-item'>"
        "  <span>Canale:</span>"
        "  <select id='pwm_ch' style='padding:6px; border-radius:4px;'><option value='1'>OUT1 (GPIO47)</option><option value='2'>OUT2 (GPIO48)</option></select>"
        "  <span>Freq (Hz):</span><input type='number' id='pwm_freq' value='1000' min='100' max='20000' style='width:80px'>"
        "  <span>Duty (%):</span><input type='number' id='pwm_duty' value='50' min='0' max='100' style='width:60px'>"
        "  <button onclick=\"setPWM()\" style='background:#2980b9'>🚀 Applica</button>"
        "</div>"

        "<div id='pwm_status' class='status-box'>Pronto per test PWM</div></div>"

        "<div id='section_rs232' class='section collapsed'><h2>📡 Seriale RS232 <span style='font-size:14px; color:#bdc3c7'>(PIN 23 TX, 35 RX)</span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span class='test-label'>Test Loopback: 0x55, 0xAA, 0x01, 0x07</span>"
        "<div class='test-controls'><button id='btn_rs232' onclick=\"toggleSimpleTest('rs232', 'btn_rs232', 'Test RS232')\">▶️ Inizia Test</button></div></div>"
        "<div class='test-item'><span>Invia Stringa (es: \\0x55\\0xAA\\r\\n)</span>"
        "<div class='test-controls'><input type='text' id='rs232_input' placeholder='\\0x55 Test...'><button onclick=\"sendSerial('rs232')\">🚀 Invia</button></div></div>"
        "<div style='display:flex; justify-content:space-between; align-items:center; margin-bottom:5px;'>"
        "  <span style='font-weight:bold;'>Monitor:</span>"
        "  <div class='test-controls'>"
        "    <select id='rs232_mode' onchange=\"clearSerial('rs232')\"><option value='HEX'>HEX</option><option value='TEXT'>TEXT</option></select>"
        "    <button onclick=\"clearSerial('rs232')\" style='background:#95a5a6; padding:4px 8px; font-size:12px;'>🗑️ Clear</button>"
        "  </div>"
        "</div>"
        "<div id='rs232_status' class='status-box'>Monitor:</div></div>"

        "<div id='section_cctalk' class='section collapsed'><h2>📡 CCtalk <span style='font-size:14px; color:#bdc3c7'>(4800 baud — PIN 21 RX, 20 TX)</span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span class='test-label'>Test Loopback: invia pacchetto di prova</span>"
        "<div class='test-controls'><button id='btn_cctalk' onclick=\"toggleSimpleTest('cctalk', 'btn_cctalk', 'Test CCtalk')\">▶️ Inizia Test</button></div></div>"
        "<div class='test-item'><span>Invia Pacchetto (es: 0x01 0x02)</span>"
        "<div class='test-controls'><input type='text' id='cctalk_input' placeholder='0x01 0x02...'><button onclick=\"sendSerial('cctalk')\">🚀 Invia</button></div></div>"
        "<div style='display:flex; justify-content:space-between; align-items:center; margin-bottom:5px;'>"
        "  <span style='font-weight:bold;'>Monitor:</span>"
        "  <div class='test-controls'>"
        "    <select id='cctalk_mode' onchange=\"clearSerial('cctalk')\"><option value='HEX'>HEX</option><option value='TEXT'>TEXT</option></select>"
        "    <button onclick=\"clearSerial('cctalk')\" style='background:#95a5a6; padding:4px 8px; font-size:12px;'>🗑️ Clear</button>"
        "  </div>"
        "</div>"
        "<div id='cctalk_status' class='status-box'>Monitor:</div></div>"

        "<div id='section_rs485' class='section collapsed'><h2>📡 Seriale RS485 <span style='font-size:14px; color:#bdc3c7'>(PIN 12 A, 17 B)</span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span class='test-label'>Test Loopback: 0x55, 0xAA, 0x01, 0x07</span>"
        "<div class='test-controls'><button id='btn_rs485' onclick=\"toggleSimpleTest('rs485', 'btn_rs485', 'Test RS485')\">▶️ Inizia Test</button></div></div>"
        "<div class='test-item'><span>Invia Stringa</span>"
        "<div class='test-controls'><input type='text' id='rs485_input' placeholder='Richiesta...'><button onclick=\"sendSerial('rs485')\">🚀 Invia</button></div></div>"
        "<div style='display:flex; justify-content:space-between; align-items:center; margin-bottom:5px;'>"
        "  <span style='font-weight:bold;'>Monitor:</span>"
        "  <div class='test-controls'>"
        "    <select id='rs485_mode' onchange=\"clearSerial('rs485')\"><option value='HEX'>HEX</option><option value='TEXT'>TEXT</option></select>"
        "    <button onclick=\"clearSerial('rs485')\" style='background:#95a5a6; padding:4px 8px; font-size:12px;'>🗑️ Clear</button>"
        "  </div>"
        "</div>"
        "<div id='rs485_status' class='status-box'>Monitor:</div></div>"

        "<div id='section_eeprom' class='section collapsed'><h2>💾 EEPROM 24LC16 <span style='font-size:14px; color:#bdc3c7'>(PIN 32, 37 / I2C)</span> <span id='eeprom_header_info' style='font-size:14px; font-weight:normal; margin-left:15px; color:#666;'></span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span>Indirizzo (0-2047)</span>"
        "<div class='test-controls'><input type='number' id='eeprom_addr' value='0' min='0' max='2047' style='width:80px'></div></div>"
        "<div class='test-item'><span>Lunghezza (bytes)</span>"
        "<div class='test-controls'><input type='number' id='eeprom_len' value='16' min='1' max='2048' style='width:80px'></div></div>"
        "<div class='test-item'><span>Dato Byte (0-255)</span>"
        "<div class='test-controls'><input type='number' id='eeprom_val' value='123' min='0' max='255' style='width:80px'>"
        "<button onclick=\"testEEPROM('write')\">✍️ Scrivi</button>"
        "<button onclick=\"testEEPROM('read')\" style='background:#3498db'>📖 Leggi</button>"
        "<button onclick=\"testEEPROM('read_json')\" style='background:#9b59b6'>📄 Leggi JSON</button>"
        "<button onclick=\"testEEPROM('dump_ascii')\" style='background:#e67e22'>🅰 Dump ASCII</button>"
        "<button onclick=\"testEEPROM('dump_hex')\" style='background:#2980b9'>🅷 Dump HEX</button>"
        "</div></div>"
        "<div id='eeprom_status' class='status-box'>Pronto per test EEPROM</div></div>"

        "<div id='section_mdb' class='section collapsed'><h2>🎰 MDB (Multi-Drop Bus) <span style='font-size:14px; color:#bdc3c7'>(PIN 8, 11)</span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span class='test-label'>Test Loopback/Echo</span>"
        "<div class='test-controls'><button id='btn_mdb' onclick=\"toggleSimpleTest('mdb', 'btn_mdb', 'Test MDB')\">▶️ Inizia Test</button></div></div>"
        "<div class='test-item'><span>Invia Stringa (Hex, es: 08 00)</span>"
        "<div class='test-controls'><input type='text' id='mdb_input' placeholder='08 00...'><button onclick=\"sendSerial('mdb')\">🚀 Invia</button></div></div>"
        "<div style='display:flex; justify-content:space-between; align-items:center; margin-bottom:5px;'>"
        "  <span style='font-weight:bold;'>Monitor:</span>"
        "  <div class='test-controls'>"
        "    <select id='mdb_mode' onchange=\"clearSerial('mdb')\"><option value='HEX'>HEX</option><option value='TEXT'>TEXT</option></select>"
        "    <button onclick=\"clearSerial('mdb')\" style='background:#95a5a6; padding:4px 8px; font-size:12px;'>🗑️ Clear</button>"
        "  </div>"
        "</div>"
        "<div id='mdb_status' class='status-box'>Pronto per test MDB</div></div>"

        "<div id='section_gpio33' class='section collapsed'><h2>🔘 GPIO Ausiliari (GPIO33)<span class='section-toggle-icon'>▸</span></h2>"
        "<div id='gpios_test_grid'>Caricamento...</div>"
        "<div id='gpios_status' class='status-box'>Stato GPIO in lettura...</div></div>"

        "<div id='section_sht40' class='section collapsed'><h2>🌡️ Sensore SHT40 <span style='font-size:14px; color:#bdc3c7'>(I2C 0x45)</span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span>Valori Correnti:</span>"
        "<div class='test-controls'><span id='sht_vals' style='font-family:monospace; font-weight:bold; color:#2ecc71'>-- °C / -- %</span></div></div>"
        "<div class='test-controls' style='justify-content:center;'>"
        "  <button onclick=\"runTest('sht_read')\" style='background:#f39c12'>🔄 FORZA TEST LETTURA</button>"
        "</div>"
        "<div id='sht_status' class='status-box'>Pronto per test SHT40</div></div>"

        "<div id='section_scanner' class='section collapsed'><h2>🔍 Scanner USB (Barcode/QR)<span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span class='test-label'>Ultime Letture</span>"
        "<div class='test-controls'>"
        "  <button type='button' onclick=\"runScannerCommand('scanner_setup')\" style='background:#8e44ad'>Scanner SETUP</button>"
        "  <button type='button' onclick=\"runScannerCommand('scanner_state')\" style='background:#3498db'>Scanner STATE</button>"
        "  <button type='button' onclick=\"runScannerCommand('scanner_on')\" style='background:#2ecc71'>Scanner ON</button>"
        "  <button type='button' onclick=\"runScannerCommand('scanner_off')\" class='btn-stop'>Scanner OFF</button>"
        "</div></div>"
        "<div style='display:flex; gap:8px; align-items:center; margin-top:6px;'>"
        "  <input id='scanner_last' type='text' readonly placeholder='Ultima lettura scanner' style='flex:1; padding:6px; font-family:monospace;'>"
        "  <button type='button' onclick=\"(async()=>{const v=document.getElementById('scanner_last').value; if(!v)return; try{ await navigator.clipboard.writeText(v); const b=document.getElementById('scanner_status'); if(b) b.innerHTML='<div class=\\'result\\'>&#x1F4CB; Copiato</div>'; }catch(e){ console.warn(e); } })()\">📋 Copia</button>"
        "</div>"
        "<div id='scanner_status' class='status-box'>Nessuna lettura ancora.</div></div>"

        "<div id='section_sd' class='section collapsed'><h2>💾 Scheda MicroSD <span style='font-size:14px; color:#bdc3c7'>(PIN 39)</span><span class='section-toggle-icon'>▸</span></h2>"
        "<div class='test-item'><span class='test-label'>Stato Montaggio:</span>"
        "<span id='sd_mounted_status' style='font-weight:bold'>--</span></div>"
        "<div class='test-item'><span class='test-label'>Ultimo Errore:</span>"
        "<span id='sd_error_status' style='color:#c0392b; font-family:monospace'>--</span></div>"
        "<div class='test-item'>"
        "<div class='test-controls'>"
        "  <button onclick=\"runTest('sd_init')\" style='background:#27ae60'>⚡ Init</button>"
        "  <button onclick='refreshSDStatus()' style='background:#3498db'>🔄 Aggiorna</button>"
        "</div></div>"
        "<div class='test-item'><span>Elenco File (Root)</span>"
        "<div class='test-controls'><button onclick=\"runTest('sd_list')\">📂 Elenca</button></div></div>"
        "<div class='test-item'><span>Backup JSON Config</span>"
        "<div class='test-controls'><button onclick=\"runConfigBackup()\" style='background:#9b59b6'>📥 Backup</button></div></div>"
        "<div class='test-item'><span style='color:#c0392b; font-weight:bold;'>⚠️ Formattazione FAT32</span>"
        "<div class='test-controls'><button onclick=\"if(confirm('Cancellare TUTTI i dati per pulire la scheda?'))runTest('sd_format')\" style='background:#c0392b'>🧨 Pulisci/Formatta</button></div>"
        "</div>"
        "<div id='sd_op_log' style='background:#000; color:#2ecc71; padding:10px; font-family:monospace; font-size:12px; height:100px; overflow-y:auto; border-radius:4px; margin-top:10px;'>Log operazioni SD...</div>"
        "<div id='sd_status' class='status-box' style='display:none'></div></div>"
        "</div>"
        "<script> (function(){document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.section>h2').forEach(function(h){h.tabIndex=0;h.addEventListener('click',function(){var s=this.parentElement; s.classList.toggle('collapsed'); var ic=this.querySelector('.section-toggle-icon'); if(ic) ic.innerText = s.classList.contains('collapsed') ? '▸' : '▾';});});}); "
        "if(typeof window.dispatchHardwareCommand!=='function'){window.dispatchHardwareCommand=function(type,payload){const detail={type:type,payload:payload||{},timestamp:Date.now()};window.dispatchEvent(new CustomEvent('emulator:hardware-command',{detail:detail}));console.log('[TEST_CMD]',detail);};}"
        "if(typeof window.runTest!=='function'){window.runTest=async function(test,params={}){try{const r=await fetch('/api/test/'+test,{method:\"POST\",body:JSON.stringify(params),headers:{\"Content-Type\":\"application/json\"}});return await r.json();}catch(e){console.error(\"runTest fallback\",e);return {error:\"fallback\"};}}}"
        "if(typeof window.runScannerCommand!=='function'){window.runScannerCommand=async function(cmd){if(window.dispatchHardwareCommand && (cmd==='scanner_on' || cmd==='scanner_off')){window.dispatchHardwareCommand(cmd,{});}try{const r=await fetch('/api/test/'+cmd,{method:\"POST\"});const res=await r.json().catch(()=>({}));const el=document.getElementById('scanner_status'); if(el) el.innerHTML = '<div class=\"result\">'+(r.ok?'✅ ':'❌ ')+ (res.message||res.error||('HTTP '+r.status)) +'</div>'; }catch(e){console.error(e);} };} })();</script>"
        "<script>"
        "let ledUpdateLock = false; let ledPendingUpdate = false;"
        "async function updateLedRealtime(){"
        "  if(ledUpdateLock) { ledPendingUpdate = true; return; }"
        "  const isRainbow = document.getElementById('btn_led_rainbow').innerText.includes('FERMA');"
        "  const isManual = document.getElementById('btn_led_manual').innerText.includes('FERMA');"
        "  if(!isRainbow && !isManual) return;"
        "  ledUpdateLock = true;"
        "  do {"
        "    ledPendingUpdate = false;"
        "    try {"
        "      const bright = document.getElementById('led_bright').value;"
        "      if(isRainbow) {"
        "        await fetch('/api/test/led_bright', {method:'POST', body: JSON.stringify({bright: parseInt(bright)})});"
        "      } else {"
        "        const color = document.getElementById('led_color').value;"
        "        await fetch('/api/test/led_set', {method:'POST', body: JSON.stringify({r: parseInt(color.substr(1,2),16), g: parseInt(color.substr(3,2),16), b: parseInt(color.substr(5,2),16), bright: parseInt(bright)})});"
        "      }"
        "    } catch(e){}"
        "  } while(ledPendingUpdate);"
        "  ledUpdateLock = false;"
        "}"

        "async function toggleLedRainbow(){"
        "  console.log('UI: toggleLedRainbow() called');"
        "  const btn = document.getElementById('btn_led_rainbow');"
        "  const isRunning = btn && btn.innerText.includes('FERMA');"
        "  const orig = btn?btn.innerHTML:null;"
        "  if(btn){ btn.disabled = true; btn.innerHTML = '⏳ Elaboro...'; }"
        "  try {"
        "    if(isRunning){"
        "      if(btn){ btn.innerText = '▶️ Inizia Rainbow'; btn.style.background = ''; }"
        "      try{ await runTest('led_stop'); } catch(e){ console.error('led_stop failed', e); }"
        "    } else {"
        "      document.getElementById('btn_led_manual').innerText = '🚀 Inizia Manuale';"
        "      document.getElementById('btn_led_manual').style.background = '#2ecc71';"
        "      if(btn){ btn.innerText = '⏹️ FERMA Rainbow'; btn.style.background = '#e74c3c'; }"
        "      const bright = document.getElementById('led_bright').value;"
        "      try{ await fetch('/api/test/led_bright', {method:'POST', body: JSON.stringify({bright: parseInt(bright)})}); }catch(e){ console.warn('led_bright post failed', e); }"
        "      try{ await runTest('led_start'); } catch(e){ console.error('led_start failed', e); }"
        "    }"
        "  } finally {"
        "    if(btn){ btn.disabled = false; if(orig) btn.innerHTML = orig; }"
        "  }"
        "}"

        "async function toggleLedManual(){"
        "  console.log('UI: toggleLedManual() called');"
        "  const btn = document.getElementById('btn_led_manual');"
        "  const isRunning = btn && btn.innerText.includes('FERMA');"
        "  const orig = btn?btn.innerHTML:null;"
        "  if(btn){ btn.disabled = true; btn.innerHTML = '⏳ Elaboro...'; }"
        "  try {"
        "    if(isRunning){"
        "      if(btn){ btn.innerText = '🚀 Inizia Manuale'; btn.style.background = '#2ecc71'; }"
        "      try{ await runTest('led_stop'); } catch(e){ console.error('led_stop failed', e); }"
        "    } else {"
        "      document.getElementById('btn_led_rainbow').innerText = '▶️ Inizia Rainbow';"
        "      document.getElementById('btn_led_rainbow').style.background = '';"
        "      if(btn){ btn.innerText = '⏹️ FERMA Manuale'; btn.style.background = '#e74c3c'; }"
        "      const color = document.getElementById('led_color').value;"
        "      const bright = document.getElementById('led_bright').value;"
        "      try{ await runTest('led_set', {r: parseInt(color.substr(1,2),16), g: parseInt(color.substr(3,2),16), b: parseInt(color.substr(5,2),16), bright: parseInt(bright)}); } catch(e){ console.error('led_set failed', e); }"
        "    }"
        "  } finally {"
        "    if(btn){ btn.disabled = false; if(orig) btn.innerHTML = orig; }"
        "  }"
        "}"

        "async function toggleSimpleTest(prefix, btnId, label){"
        "  console.log('UI: toggleSimpleTest()', prefix, btnId, label);"
        "  const btn = document.getElementById(btnId);"
        "  if(!btn) return; const orig = btn.innerHTML;"
        "  const isRunning = btn.innerText.includes('FERMA');"
        "  btn.disabled = true; btn.innerHTML = '⏳ Elaboro...';"
        "  try{"
        "    if(isRunning){"
        "      btn.innerText = '▶️ Inizia ' + label; btn.style.background = '';"
        "      try{ await runTest(prefix + '_stop'); } catch(e){ console.error(prefix + '_stop failed', e); }"
        "    } else {"
        "      btn.innerText = '⏹️ FERMA ' + label; btn.style.background = '#e74c3c';"
        "      try{ await runTest(prefix + '_start'); } catch(e){ console.error(prefix + '_start failed', e); }"
        "    }"
        "  } finally { btn.disabled = false; if(orig) btn.innerHTML = orig; }"
        "}"

        "async function fetchJsonWithTimeout(url,opts,timeoutMs){const ctrl=new AbortController();const t=setTimeout(function(){ctrl.abort();},timeoutMs||8000);try{const r=await fetch(url,Object.assign({},opts||{},{signal:ctrl.signal}));const json=await r.json().catch(function(){return {error:'Risposta JSON non valida'};});return {ok:r.ok,status:r.status,json:json};}catch(e){if(e&&e.name==='AbortError'){return {ok:false,status:0,json:{error:'Timeout richiesta'}};}throw e;}finally{clearTimeout(t);}}"

        "async function runTest(test,params={}){"
        "try{"
        "const isSd = test.startsWith('sd_');"
        "const url='/api/test/'+test;const statusId=test.split('_')[0]+'_status';"
        "const statusBox=document.getElementById(statusId);"
        "const sdLog=document.getElementById('sd_op_log');"

        "if(isSd && sdLog){"
        "  const time = new Date().toLocaleTimeString();"
        "  sdLog.innerHTML += '<div>['+time+'] INVIO: '+test+'...</div>';"
        "  sdLog.scrollTop = sdLog.scrollHeight;"
        "  if(test==='sd_format') window.sdFmtInterval = setInterval(refreshSDStatus, 1000);"
        "}"

        "if(!isSd && statusBox){"
        "  statusBox.innerHTML+='<div class=\"result\">➡️ Esecuzione: '+test+'...</div>';"
        "  statusBox.scrollTop=statusBox.scrollHeight;"
        "}"

        "const fr=await fetchJsonWithTimeout(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(params)},12000);"
        "const r={ok:fr.ok,status:fr.status};"
        "const result=fr.json||{error:'Risposta JSON non valida'};"
        "const time = new Date().toLocaleTimeString();"

        "if(r.ok){"
        "  if(isSd && sdLog){"
        "    sdLog.innerHTML += '<div style=\"color:#fff\">['+time+'] ✅ '+(result.message||'OK')+'</div>';"
        "    refreshSDStatus();"
        "  } else if(test==='sht_read') {"
        "    document.getElementById('sht_vals').innerText = result.temperature.toFixed(1)+' °C / '+result.humidity.toFixed(1)+' %';"
        "    if(statusBox) statusBox.innerHTML+='<div class=\"result\">✅ Lettura OK</div>';"
        "  } else if(statusBox) statusBox.innerHTML+='<div class=\"result\">✅ '+(result.message||'OK')+'</div>';"
        "}else{"
        "  if(isSd && sdLog){"
        "    sdLog.innerHTML += '<div style=\"color:#e74c3c\">['+time+'] ❌ Errore: '+(result.error||r.status)+'</div>';"
        "  } else if(statusBox) statusBox.innerHTML+='<div class=\"result\">❌ Errore: '+(result.error||r.status)+'</div>';"
        "}"
        "if(statusBox) statusBox.scrollTop=statusBox.scrollHeight;"
        "if(sdLog) sdLog.scrollTop=sdLog.scrollHeight;"
        "}catch(e){console.error(e);}}"

        "async function sendSerial(port){"
        "  console.log('UI: sendSerial()', port);"
        "  const caller = document.activeElement; const btn = (caller && caller.tagName==='BUTTON')?caller:null; const orig = btn?btn.innerHTML:null; if(btn){ btn.disabled=true; btn.innerHTML='⏳ Inviando...'; }"
        "  try{"
        "    const data = document.getElementById(port + '_input').value;"
        "    await fetch('/api/test/serial_send',{method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({port,data})});"
        "    const st = document.getElementById(port + '_status'); if(st) st.innerHTML = '<div class=\"result\">Inviato: '+(data||'')+'</div>';"
        "  }catch(e){ console.error(e); const st = document.getElementById(port + '_status'); if(st) st.innerHTML = '<div class=\"result\">Errore: '+e+'</div>'; }"
        "  finally{ if(btn){ btn.disabled=false; btn.innerHTML = orig; } }"
        "}"

        "async function updateMonitors(){"
        "/* display brightness slider handler (debounced + persist after idle) */"
        "let __dispBrightTimer = null; let __dispBrightPersistTimer = null;"
        "window.onDisplayBrightInput = function(val){"
        "  document.getElementById('bright_val').innerText = val;"
        "  /* live update to hardware (short debounce) */"
        "  if(__dispBrightTimer) clearTimeout(__dispBrightTimer);"
        "  __dispBrightTimer = setTimeout(async function(){"
        "    try{ await fetch('/api/test/display_bright',{method:'POST',body:JSON.stringify({bright: parseInt(val)})}); }catch(e){}"
        "  }, 120);"
        "  /* schedule persistence after 5s of inactivity */"
        "  if(__dispBrightPersistTimer) clearTimeout(__dispBrightPersistTimer);"
        "  __dispBrightPersistTimer = setTimeout(async function(){"
        "    try{"
        "      const cfg = { display: { enabled: document.getElementById('display_en').checked, lcd_brightness: parseInt(val) } };"
        "      const r = await fetch('/api/config/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});"
        "      if(r.ok){ const a=document.getElementById('alert'); if(a){ a.innerText='✅ Luminosità salvata'; a.className='success'; setTimeout(()=>{ a.innerText=''; a.className=''; },2000); } }"
        "    }catch(e){}"
        "  }, 5000);"
        "};"
        "try{"
        "const mon=await fetchJsonWithTimeout('/api/test/serial_monitor',{method:'POST'},6000);"
        "if(!mon.ok)return;"
        "const res=mon.json||{};"
        "const processLog = (log, modeId) => {"
        "  if(!log || !document.getElementById(modeId)) return '';"
        "  const mode = document.getElementById(modeId).value;"
        "  const parts = log.split('|');"
        "  let out = '';"
        "  for(let i=0; i<parts.length-2; i+=3) {"
        "    const prefix = parts[i]; const hex = parts[i+1]; const text = parts[i+2];"
        "    const isRx = prefix.startsWith('RX');"
        "    const color = isRx ? '#f1c40f' : '#ff4d4d';"
        "    if(mode === 'HEX') out += '<span style=\"color:'+color+'\">.' + hex + '</span>';"
        "    else out += '<span style=\"color:'+color+'\">' + text + '</span>';"
        "  }"
        "  return out;"
        "};"
        "if(res.rs232) { const el=document.getElementById('rs232_status'); el.innerHTML=processLog(res.rs232, 'rs232_mode'); el.scrollTop=el.scrollHeight; }"
        "if(res.rs485) { const el=document.getElementById('rs485_status'); el.innerHTML=processLog(res.rs485, 'rs485_mode'); el.scrollTop=el.scrollHeight; }"
        "if(res.mdb) { const el=document.getElementById('mdb_status'); el.innerHTML=processLog(res.mdb, 'mdb_mode'); el.scrollTop=el.scrollHeight; }"
        "if(res.cctalk) { const el=document.getElementById('cctalk_status'); if(el) { el.innerHTML = processLog(res.cctalk, 'cctalk_mode'); el.scrollTop = el.scrollHeight; } }"
        "const rio=await fetchJsonWithTimeout('/api/test/io_get',{method:'POST'},6000);"
        "const io=rio.json||{};"
        "if(io){"
        "  const out_grid = document.getElementById('outputs_grid');"
        "  const in_grid = document.getElementById('inputs_grid');"
        "  if(out_grid && out_grid.children.length === 0){"
        "    for(let i=0;i<8;i++){"
        "      let b = document.createElement('button');"
        "      b.innerText = 'OUT'+i;"
        "      b.id = 'out_btn_'+i;"
        "      b.onclick = () => toggleIO(i);"
        "      out_grid.appendChild(b);"
        "      let s = document.createElement('span');"
        "      s.id = 'in_val_'+i;"
        "      s.style = 'padding:8px; border:1px solid #ccc; border-radius:4px; min-width:40px; text-align:center; background:#eee; color:#333;';"
        "      s.innerText = 'IN'+i;"
        "      in_grid.appendChild(s);"
        "    }"
        "  }"
        "  for(let i=0;i<8;i++){"
        "    const b = document.getElementById('out_btn_'+i);"
        "    if(b) b.style.background = ((io.output >> i) & 1) ? '#2ecc71' : '#95a5a6';"
        "    const s = document.getElementById('in_val_'+i);"
        "    if(s){"
        "      const on = (io.input >> i) & 1;"
        "      s.style.background = on ? '#2ecc71' : '#34495e';"
        "      s.style.color = on ? '#fff' : '#bdc3c7';"
        "    }"
        "  }"
        "}"
        "}catch(e){}}"

        "async function toggleIO(pin){"
        "try{"
        "const rio=await fetch('/api/test/io_get',{method:'POST'});"
        "const io=await rio.json();"
        "const cur = (io.output >> pin) & 1;"
        "await fetch('/api/test/io_set',{method:'POST',body:JSON.stringify({pin:pin, val:cur?0:1})});"
        "}catch(e){}}"

        "async function setPWM(){"
        "try{"
        "const ch=parseInt(document.getElementById('pwm_ch').value);"
        "const freq=parseInt(document.getElementById('pwm_freq').value);"
        "const duty=parseInt(document.getElementById('pwm_duty').value);"
        "await fetch('/api/test/pwm_set',{method:'POST',body:JSON.stringify({ch,freq,duty})});"
        "}catch(e){}}"

        "async function testEEPROM(op){"
        "try{"
        "const addr=parseInt(document.getElementById('eeprom_addr').value);"
        "const val=parseInt(document.getElementById('eeprom_val').value);"
        "const statusBox=document.getElementById('eeprom_status');"
        "let body={op:op, addr:addr};"
        "if(op==='write') body.data=[val]; else body.len=1;"
        "if(op==='dump_ascii' || op==='dump_hex') { const len=parseInt(document.getElementById('eeprom_len')?.value||0); if(len>0) body.len=len; }"
        "const r=await fetch('/api/test/eeprom',{method:'POST',body:JSON.stringify(body)});"
        "const res=await r.json();"
        "if(res.status==='ok'){"
        "  if(op==='read') statusBox.innerHTML='<div class=\"result\">📖 Letto da '+addr+': <b>'+res.data[0]+'</b> (0x'+res.data[0].toString(16).toUpperCase()+')</div>';"
        "  else if(op==='read_json') statusBox.innerHTML='<div class=\"result\">📄 Config JSON:<br><pre style=\"background:#002244;color:#00ff00;padding:10px;border-radius:4px;overflow-x:auto;margin:5px 0;font-size:11px\">'+JSON.stringify(JSON.parse(res.json),null,2)+'</pre></div>';"
        "  else if(op==='dump_ascii') statusBox.innerHTML='<div class=\"result\">🅰 ASCII Dump:<br><pre style=\"background:#002244;color:#00ff00;padding:10px;border-radius:4px;overflow-x:auto;margin:5px 0;font-size:11px\">'+res.ascii+'</pre></div>';"
        "  else if(op==='dump_hex') {"
        "    let data = res.data || [];"
        "    let html = '<pre style=\"font-family:monospace;\">';"
        "    for(let i=0;i<data.length;i+=16){"
        "      let lineAddr = addr + i;"
        "      html += ('0000'+lineAddr.toString(16).toUpperCase()).slice(-4) + ': ';"
        "      for(let j=0;j<16 && i+j<data.length;j++){"
        "        let b = data[i+j];"
        "        let color = ((i+j)%2===0)?'#000':'#00f';"
        "        html += '<span style=\"color:'+color+'\">'+('00'+b.toString(16).toUpperCase()).slice(-2)+'</span> ';"
        "      }"
        "      html += '<br>';"
        "    }"
        "    html += '</pre>';"
        "    statusBox.innerHTML='<div class=\"result\">🅷 HEX Dump:<br>'+html+'</div>';"
        "  } else statusBox.innerHTML='<div class=\"result\">✅ Scritto '+val+' a '+addr+'</div>';"
        "  refreshEEPROMStatus();"
        "}else statusBox.innerHTML='<div class=\"result\">❌ Errore</div>';"
        "}catch(e){console.error(e);}}"

        "async function runConfigBackup(){"
        "try{"
        "  const statusBox=document.getElementById('sd_status');"
        "  statusBox.innerHTML+='<div class=\"result\">➡️ Invio Backup...</div>';"
        "  const r=await fetch('/api/config/backup',{method:'POST'});"
        "  const res=await r.json();"
        "  if(r.ok) statusBox.innerHTML+='<div class=\"result\">✅ OK</div>';"
        "  else statusBox.innerHTML+='<div class=\"result\">❌ '+r.status+'</div>';"
        "}catch(e){}}"

        "async function clearSerial(port){"
        "  console.log('UI: clearSerial()', port);"
        "  const caller = document.activeElement; const btn = (caller && caller.tagName==='BUTTON')?caller:null; const orig = btn?btn.innerHTML:null; if(btn){ btn.disabled=true; btn.innerHTML='⏳ Pulendo...'; }"
        "  try{"
        "    /* Pulisce immediatamente l'area di testo lato client */"
        "    const elId = port + '_status';"
        "    const el = document.getElementById(elId);"
        "    if(el) el.innerHTML = '';"
        "    /* Poi pulisce lato server */"
        "    await fetch('/api/test/serial_clear',{method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({port})});"
        "  }catch(e){ console.error(e); } finally { if(btn){ btn.disabled=false; btn.innerHTML = orig; } }"
        "}"

        "async function refreshEEPROMStatus(){"
        "try{"
        "  const r=await fetch('/api/test/eeprom',{method:'POST',body:JSON.stringify({op:'status'})});"
        "  const res=await r.json();"
        "  if(res.status==='ok') document.getElementById('eeprom_header_info').innerText='CRC: 0x'+res.crc.toString(16).toUpperCase();"
        "}catch(e){}}"

        "/* Scanner UI: mostra le ultime letture (tag 'SCANNER') e comandi ON/OFF */"
        "async function updateScannerReadings(){"
        "try{const r=await fetch('/api/logs'); if(!r.ok) return; const logs=await r.json(); const scannerLogs = logs.filter(l=> (l.tag==='SCANNER_DATA' || l.tag==='SCANNER') && !/API scanner_/.test(l.message)); if(scannerLogs.length===0){ document.getElementById('scanner_status').innerText='Nessuna lettura ancora.'; const tb=document.getElementById('scanner_last'); if(tb) tb.value=''; return;} let html=''; const last = scannerLogs.slice(-10); last.reverse().forEach(l=>{ html += '<div class=\"result\">['+l.timestamp+'] '+l.message+'</div>'; }); document.getElementById('scanner_status').innerHTML = html; /* populate readonly textbox with the most recent reading */ const mostRecent = scannerLogs[scannerLogs.length-1]; const tb=document.getElementById('scanner_last'); if(tb) tb.value = (mostRecent.message || '').replace(/[^ -~]/g, ''); /* strip non-printable/control chars */ }catch(e){console.error(e);}}"

        "async function runScannerCommand(cmd){"
        "try{"
        " const r=await fetch('/api/test/'+cmd,{method:'POST'});"
        " const res=await r.json();"
        " const ok=(r.ok && (!res.status || res.status==='ok'));"
        " const msg=(res && (res.message||res.error||res.err)) ? (res.message||res.error||res.err) : ('HTTP '+r.status);"
        " document.getElementById('scanner_status').innerHTML='<div class=\"result\">'+(ok?'✅ ':'❌ ')+msg+'</div>';"
        "}catch(e){document.getElementById('scanner_status').innerHTML='<div class=\"result\">❌ Errore comando scanner</div>';console.error(e);}"
        "}"

        "/* avvia aggiornamenti periodici per la sezione Scanner */"
        "updateScannerReadings(); setInterval(updateScannerReadings, 1000);"
        "/* Hide /test sections when corresponding peripheral is disabled in /config */"
        "(async function hideDisabledSections(){ try{"
        "  const r = await fetch('/api/config'); if(!r.ok) return; const c = await r.json();"
        "  /* sensors */"
        "  if(c.sensors){"
        "    if(!c.sensors.led_enabled){ const s=document.getElementById('section_led'); if(s) s.style.display='none'; }"
        "    if(!c.sensors.io_expander_enabled){ const s=document.getElementById('section_ioexp'); if(s) s.style.display='none'; }"
        "    if(!c.sensors.pwm1_enabled && !c.sensors.pwm2_enabled){ const s=document.getElementById('section_pwm'); if(s) s.style.display='none'; }"
        "    if(!c.sensors.rs232_enabled){ const s=document.getElementById('section_rs232'); if(s) s.style.display='none'; }"
        "    if(!c.sensors.rs485_enabled){ const s=document.getElementById('section_rs485'); if(s) s.style.display='none'; }"
        "    if(!c.sensors.mdb_enabled){ const s=document.getElementById('section_mdb'); if(s) s.style.display='none'; }"
        "    if(typeof c.sensors.eeprom_enabled !== 'undefined' && !c.sensors.eeprom_enabled){ const s=document.getElementById('section_eeprom'); if(s) s.style.display='none'; }"
        "    if(!c.sensors.sd_card_enabled){ const s=document.getElementById('section_sd'); if(s) s.style.display='none'; }"
        "  }"
        "  /* scanner */ if(c.scanner){ if(!c.scanner.enabled){ const s=document.getElementById('section_scanner'); if(s) s.style.display='none'; }}"
        "  /* GPIO/SHT */ if(c.gpios){ if(c.gpios.gpio33 && c.gpios.gpio33.mode === 3){ } else { const s=document.getElementById('section_gpio33'); if(s) s.style.display='none'; } }"
        "  if(typeof c.sensors !== 'undefined' && !c.sensors.temperature_enabled){ const s=document.getElementById('section_sht40'); if(s) s.style.display='none'; }"
        " }catch(e){console.warn('hideDisabledSections',e);} })();"

        "async function refreshSDStatus(){"
        "try{"
        "  const sr=await fetchJsonWithTimeout('/status',{},6000);"
        "  if(!sr.ok||!sr.json||!sr.json.sd){return;}"
        "  const res=sr.json;"
        "  const el=document.getElementById('sd_mounted_status');"
        "  if(el) {"
        "    if(res.sd.mounted) el.innerText = '✅ MONTATA';"
        "    else if(res.sd.present) el.innerText = '⚠️ PRESENTE (NON MONTATA)';"
        "    else el.innerText = '❌ ASSENTE';"
        "  }"
        "  const errEl=document.getElementById('sd_error_status');"
        "  if(errEl) {"
        "    if(errEl.innerText !== res.sd.last_error && res.sd.last_error !== 'Nessuno') {"
        "       const sdLog=document.getElementById('sd_op_log');"
        "       if(sdLog) {"
        "         const time = new Date().toLocaleTimeString();"
        "         sdLog.innerHTML += '<div>['+time+'] STATO: '+res.sd.last_error+'</div>';"
        "         sdLog.scrollTop = sdLog.scrollHeight;"
        "       }"
        "    }"
        "    errEl.innerText = res.sd.last_error;"
        "  }"
        "  if(window.sdFmtInterval && (res.sd.last_error.includes('OK') || res.sd.last_error.includes('Errore'))){"
        "    clearInterval(window.sdFmtInterval); window.sdFmtInterval=null;"
        "  }"
        "}catch(e){}}"

        "async function updateGPIOs(){"
        "try{"
        "  const sr=await fetchJsonWithTimeout('/status',{},6000);"
        "  if(!sr.ok||!sr.json){return;}"
        "  const s=sr.json;"
        "  const gr=await fetchJsonWithTimeout('/api/test/gpio_get',{method:'POST'},6000);"
        "  if(!gr.ok||!gr.json){return;}"
        "  const gpios=gr.json;"
        "  let h='';"
        "  [33].forEach(pin=>{"
        "    const cfg = gpios[pin];"
        "    const isOut = cfg.mode === 3;"
        "    const val = cfg.level;"
        "    h+='<div class=\"test-item\"><span class=\"test-label\">GPIO '+pin+' ('+(isOut?'OUT':'IN')+')</span>';"
        "    h+='<div class=\"test-controls\"><span style=\"background:'+(val?'#2ecc71':'#34495e')+';color:white;padding:4px 8px;border-radius:4px;\">'+(val?'HIGH':'LOW')+'</span>';"
        "    if(isOut) h+='<button onclick=\"setAuxGPIO('+pin+',1)\">ON</button><button onclick=\"setAuxGPIO('+pin+',0)\" style=\"background:#95a5a6\">OFF</button>';"
        "    h+='</div></div>';"
        "  });"
        "  document.getElementById('gpios_test_grid').innerHTML=h;"
        "  const el=document.getElementById('sht_vals');"
        "  if(el) el.innerText=s.env.temp.toFixed(1)+' °C / '+s.env.hum.toFixed(1)+' %';"
        "}catch(e){}}"

        "async function setAuxGPIO(pin,val){"
        "try{ await fetch('/api/test/gpio_set',{method:'POST',body:JSON.stringify({pin,val})}); updateGPIOs();"
        "}catch(e){}}"

        "refreshEEPROMStatus();"
        "refreshSDStatus();"
        "setInterval(updateMonitors, 1000);"
        "setInterval(updateGPIOs, 1000);"
        "</script></body></html>";

    httpd_resp_sendstr_chunk(req, body);
    httpd_resp_sendstr_chunk(req, NULL);
    return ESP_OK;
}
